name: build_debs

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  build-debian-buster:    
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config:
          - os: debian
            arch: amd64
            dist: buster
          - os: debian
            arch: armhf
            dist: buster
          - os: debian
            arch: arm64
            dist: buster
          - os: raspbian
            arch: armhf
            dist: buster
    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt update
    - name: apt
      run: >
        sudo apt-get install qemu 
        binfmt-support qemu-user-static 
        pbuilder debootstrap devscripts git-buildpackage 
        debian-keyring  debian-archive-keyring dh-make -qq
    - name: cp pbuilderrc
      run: |
        cp pbuilderrc $HOME/.pbuilderrc
        sudo cp pbuilderrc /root/.pbuilderrc
    - name: pbuilder-create
      run: |
        sudo mkdir -p /var/cache/pbuilder/debian-buster-amd64/aptcache/
        sudo OS=${{ matrix.config.os }} DIST=${{ matrix.config.dist }} ARCH=${{ matrix.config.arch }} pbuilder --create
    - name: extact-source-deb
      run: |
        dpkg-source -x robotraconteur_*~buster.dsc src_deb
    - name: pubilder-build
      working-directory: src_deb
      run: |
        OS=${{ matrix.config.os }} DIST=${{ matrix.config.dist }} ARCH=${{ matrix.config.arch }} pdebuild
    - name: archive result
      uses: actions/upload-artifact@v2
      with:
        name: 'result-debian-buster-amd64'
        path: result/*