name: build_debs

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  build-debian-buster:    
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt update
    - name: apt
      run: >
        sudo apt-get install qemu 
        binfmt-support qemu-user-static 
        pbuilder debootstrap devscripts git-buildpackage 
        debian-keyring  debian-archive-keyring -qq

    - name: pbuilder-create
      run: |
        sudo mkdir -p /var/cache/pbuilder/debian-buster-amd64/aptcache/
        sudo OS=debian DIST=buster ARCH=amd64 pbuilder --create --configfile $GITHUB_WORKSPACE/pbuilderrc
    - name: extact-source-deb
      run: |
        mkdir src_deb
        dpkg-source -x robotraconteur_*~buster.dsc src_deb
    - name: pubilder-build
      working-directory: src_deb
      run: |
        OS=debian DIST=buster ARCH=amd64 pdebuild --configfile $GITHUB_WORKSPACE/pbuilderrc
    - name: archive result
      uses: actions/upload-artifact@v2
      with:
        name: 'result-debian-buster-amd64'
        path: result/*